### ISSUE TITLE
unicode support in formatter.py

### ISSUE THREAD

**Issue by rrey** [vklochan/python-logstash#70] opened 2017-06-12 14:35 UTC
Hello,

```
Name: python-logstash
Version: 0.4.6
Summary: Python logging handler for Logstash.
Home-page: https://github.com/vklochan/python-logstash
Author: Volodymyr Klochan
Author-email: vklochan@gmail.com
License: UNKNOWN
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
```

Using python-logstash through ansible logstash call back I get the following error:

```
TASK [java/jdk : Préparation répertoire destination Java] ***********************************************************************************************************************************************************************************
changed: [tnr-container]
TASK: java/jdk : Préparation répertoire destination Java
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 578, in emit
    s = self.makePickle(record)
  File "/usr/local/lib/python2.7/dist-packages/logstash/handler_tcp.py", line 25, in makePickle
    return self.formatter.format(record) + b'\n'
  File "/usr/local/lib/python2.7/dist-packages/logstash/formatter.py", line 136, in format
    message.update(self.get_extra_fields(record))
  File "/usr/local/lib/python2.7/dist-packages/logstash/formatter.py", line 45, in get_extra_fields
    fields[key] = repr(value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 19: ordinal not in range(128)
Logged from file logstash.py, line 131

```

The problem comes from the latin1 character present in the handled value.

**Comment by RomkaSk** [comment] 2023-07-27 15:57
I can't reproduce it for python3. If you want to use latin1 you should set the global encoding as utf-8 for the interpreter. See https://docs.python.org/2.7/using/cmdline.html#envvar-PYTHONIOENCODING

**Comment by vklochan** [comment] 2023-08-11 17:29
Closing this issue based on the prev comment.

**Closed by vklochan** 2023-08-11 17:29 UTC
